---
- hosts: masters,workers,ingress
  become: yes
  gather_facts: yes

  # TODO:
  # - add podman an buildah and crictl

  tasks:
    - name: Creates /etc/modules-load.d directory
      file:
        path: /etc/modules-load.d
        state: directory

    - name: configure containerd.conf modules to use
      copy:
        src: 'containerd.conf.tmpl'
        dest: '/etc/modules-load.d/containerd.conf'

    - name: Apply params without reboot
      command: '{{ item }}'
      with_items:
        - modprobe overlay
        - modprobe br_netfilter

    - name: Creates /etc/sysctl.d directory
      file:
        path: /etc/sysctl.d
        state: directory

    - name: Setup required sysctl params, these persist across reboots.
      copy:
        src: 'kubernetes.conf.tmpl'
        dest: '/etc/sysctl.d/kubernetes.conf'

    - name: Apply sysctl params without reboot
      command: '{{ item }}'
      with_items:
        - sysctl --system

    - name: Installing Prerequisites for containerd and k8s
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker/Containerd Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker
        mode: 0600

    - name: Install Containerd Engine from Docker-Repo
      apt:
        name:
          - containerd.io=1.5.11-1 # new version has a bug and won´t work - latest working is 1.5.11, but no repo is there
        state: present
        update_cache: yes

    - name: Creates /etc/containerd directory
      file:
        path: /etc/containerd
        state: directory

    - name: create a default containerd config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

    #   - name: Create a default-config for containerd
    #     command: "{{ item }}"
    #     with_items:
    #        - containerd config default | sudo tee /etc/containerd/config.tomld/config.toml'

    - name: Enable service containerd, and enable persistently
      ansible.builtin.systemd:
        name: containerd
        enabled: yes
        state: started
