---
- hosts: masters,workers,ingress
  become: yes
  gather_facts: yes

  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Make the Swap inactive
      command: swapoff -a

    - name: Remove Swap entry from /etc/fstab.
      lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent

    - name: Installing Prerequisites for Kubernetes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - vim
          - software-properties-common
          - nfs-common
        state: present

    - name: Add Google official GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes Repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        mode: 0600
        update_cache: yes

    - name: Installing Kubernetes Cluster Packages.
      apt:
        name:
          - kubeadm=1.23.4-00
          - kubectl=1.23.4-00
          - kubelet=1.23.4-00
        state: present

      # Kept multiple packages back (hold packages)
    - dpkg_selections: name={{ item }} selection=hold
      with_items:
        - kubeadm
        - kubectl
        - kubelet

    - name: Letting iptables see bridged traffic - 1
      copy:
        src: 'k8s.conf.tmpl'
        dest: '/etc/modules-load.d/k8s.conf'

    - name: Letting iptables see bridged traffic - 2
      copy:
        src: 'k8s.conf.sysctl.tmpl'
        dest: '/etc/sysctl.d/k8s.conf'

    - name: Apply sysctl params without reboot
      command: '{{ item }}'
      with_items:
        - sysctl --system

    - name: Copy a prepared kubeadm-config.yaml for kickstart the installation
      when: inventory_hostname in groups['masters']
      copy:
        src: 'kubeadm-config.yaml.tmpl'
        dest: '/root/kubeadm-config.yaml'

    - name: Copy a prepared calico.yaml for kickstart the CNI-Installation
      when: inventory_hostname in groups['masters']
      copy:
        src: 'calico.yaml.tmpl'
        dest: '/root/calico.yaml'

    - name: Copy a prepared haproxy.yaml for kickstart the Ingress-Installation
      when: inventory_hostname in groups['masters']
      copy:
        src: 'haproxy.yaml.tmpl'
        dest: '/root/haproxy.yaml'

    - name: Copy a prepared copy-shell
      when: inventory_hostname in groups['masters']
      copy:
        src: 'copy-kube-config.sh'
        dest: '/root/copy-kube-config.sh'

    - name: Reboot the machine (Wait for 1 min)
      reboot:
        reboot_timeout: 60
  roles:
    - robertdebock.fail2ban
